# Mapping team IDs from the web link to team abbreviations used in the API
TEAM_ID_MAP = {
    -1: "FA",
    0: "BAL",
    1: "BOS",
    2: "NYY",
    3: "TB",
    4: "TOR",
    5: "CWS",
    6: "CLE",
    7: "DET",
    8: "KC",
    9: "MIN",
    10: "HOU",
    11: "LAA",
    12: "OAK",
    13: "SEA",
    14: "TEX",
    15: "ATL",
    16: "MIA",
    17: "NYM",
    18: "PHI",
    19: "WAS",
    20: "CHC",
    21: "CIN",
    22: "MIL",
    23: "PIT",
    24: "STL",
    25: "ARI",
    26: "COL",
    27: "LAD",
    28: "SD",
    29: "SF",
}
